@Ticketing.Command_HostAddress = http://localhost:5001

POST {{ Ticketing.Command_HostAddress }}/api/ticket
Accept: application/json
Content-Type: application/json
{
    "username": "jose.perez@gmail.com",
    "typeError": 1,
    "detailError": "El teclado no funciona"
}

###

PUT {{ Ticketing.Command_HostAddress }}/api/ticket/01958981-d0e0-76d7-b9c0-8156938f8fde
Accept: application/json
Content-Type: application/json

{
  "ticketType": 5,
  "description": "El error continua, enviar el respuesto",
  "username": "julio.gomez@gmail.com"
}