@Ticketing.Command_HostAddress = http://localhost:5001

POST {{ Ticketing.Command_HostAddress }}/api/ticket
Accept: application/json
Content-Type: application/json
{
    "username": "jose.perez@gmail.com",
    "typeError": 1,
    "detailError": "El teclado no funciona"
}

###
